INSERT INTO internships (title, skills_required, description, category) VALUES
('Frontend Developer Internship', 'React, Tailwind CSS, HTML, CSS, JavaScript, Git', 'Work on modern UI with React and Tailwind.', 'Frontend Development'),
('Backend Developer Internship', 'Node.js, Express.js, RESTful APIs, SQL/NoSQL databases, Git, Docker', 'Build scalable APIs and microservices.', 'Backend Development'),
('React.js Developer Internship', 'React.js, JavaScript, Redux, HTML, CSS, Git', 'Create component-based UIs using React.', 'Frontend Development'),
('Python Development Internship', 'Python, Django/Flask, REST APIs, SQL/NoSQL databases, Git, Docker', 'Develop backend services with Python.', 'Backend Development'),
('MERN Stack Developer Internship', 'MongoDB, Express.js, React.js, Node.js, JavaScript, REST APIs, Git, Docker', 'Full-stack development with MERN.', 'Full Stack Development'),
('Spring Boot Development Internship', 'Java, Spring Boot, REST APIs, SQL/NoSQL databases, Git, Maven, Docker', 'Build APIs using Spring Boot.', 'Backend Development'),
('Software Testing Internship', 'Manual Testing, Automated Testing, Selenium, JUnit, TestNG, Bug Tracking Tools, Git', 'Ensure quality through testing.', 'Quality Assurance'),
('WIX Web Development Internship', 'Wix, HTML, CSS, JavaScript, SEO, Graphic Design, UX/UI Design', 'Create websites with Wix platform.', 'Web Development'),
('MEAN Stack Developer Internship', 'MongoDB, Express.js, Angular, Node.js, JavaScript, REST APIs, Git, Docker', 'Full-stack development with MEAN.', 'Full Stack Development'),
('JAVA Developer Internship', 'Java, Spring Framework, REST APIs, SQL/NoSQL databases, Git, Maven, Docker', 'Develop Java-based applications.', 'Backend Development'),
('Node.js Developer Internship', 'Node.js, Express.js, JavaScript, REST APIs, SQL/NoSQL databases, Git, Docker', 'Build backend services in Node.', 'Backend Development'),
('Android Developer Internship', 'Java/Kotlin, Android Studio, XML, REST APIs, Git, Firebase, SQLite', 'Create Android apps.', 'Mobile Development'),
('WordPress Development Internship', 'WordPress, PHP, HTML, CSS, JavaScript, MySQL, SEO, Git', 'Build and customize WP sites.', 'Web Development'),
('Angular Development Internship', 'Angular, TypeScript, HTML, CSS, JavaScript, REST APIs, Git, Webpack', 'Develop Angular applications.', 'Frontend Development'),
('Data Structure Internship', 'Data Structures, Algorithms, Java/Python/C++, Problem Solving, Git', 'Strengthen CS fundamentals.', 'Software Development'),
('C/C++ Development Internship', 'C/C++, Data Structures, Algorithms, Problem Solving, Git, Debugging Tools', 'Systems programming with C/C++.', 'Software Development'),
('Artificial Intelligence Internship', 'Machine Learning, Python, TensorFlow/PyTorch, Data Analysis, Git', 'Work on ML models and pipelines.', 'AI/ML'),
('Data Science and Machine Learning Internship', 'Python/R, Data Analysis, Machine Learning, SQL, Pandas, Scikit-learn, Git', 'Analyze data and build models.', 'Data Science'),
('Big Data Internship', 'Hadoop, Spark, Python/Java, SQL, Data Analysis, ETL, Git', 'Process large-scale datasets.', 'Data Engineering'),
('Cloud Computing Internship', 'AWS/Azure/GCP, Cloud Architecture, Docker, Kubernetes, DevOps, Git', 'Cloud-native development and ops.', 'Cloud/DevOps'),
('Software Development Internship', 'Java/Python/C++, Software Development, SQL/NoSQL, Git, Agile Methodologies', 'General software engineering.', 'Software Development'),
('Technical Program Management Internship', 'Project Management, Agile Methodologies, Communication, Jira, Confluence', 'Manage technical programs.', 'Program Management'),
('DevOps Engineering Internship', 'Linux, Docker, Kubernetes, Jenkins, AWS/Azure/GCP, Scripting, Git', 'CI/CD and infrastructure automation.', 'Cloud/DevOps'),
('Data Analysis Internship', 'Python, R, Pandas, NumPy, Matplotlib, Tableau, Data Analysis, Data Visualization', 'Analyze and visualize data.', 'Data Science');